services:
  - type: web
    name: fastapi-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: esg-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  - type: web
    name: react-frontend
    runtime: static
    buildCommand: |
      echo "SKIP_PREFLIGHT_CHECK=true" > .env
      echo "REACT_APP_API_URL=$API_URL" >> .env
      npm install --legacy-peer-deps
      npm run build
    staticPublishPath: ./build
    envVars:
      - key: API_URL
        value: "https://seu-backend.onrender.com"