name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ENVIRONMENT: "test"
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Python tests
        run: |
          pytest backend/tests/ -v

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    needs: test-backend
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install Node dependencies
        run: |
          npm cache clean --force
          npm install --legacy-peer-deps

      - name: Create env file
        run: |
          echo "REACT_APP_API_URL=${{ secrets.API_URL }}" > .env
          echo "SKIP_PREFLIGHT_CHECK=true" >> .env

      - name: Build frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
